"""
Phase 2 — Data Statistics & Quality Reports.

Generates:
  reports/data_quality.md  — schema, nulls, dtype issues
  reports/data_stats.md    — split counts, length distributions
  reports/figures/         — PNG charts (message length, thread length)
"""
from __future__ import annotations

import textwrap
from pathlib import Path

import matplotlib
matplotlib.use("Agg")  # non-interactive backend — works without a display
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.config.settings import settings
from src.data.threads import Thread


# ---------------------------------------------------------------------------
# Data quality report
# ---------------------------------------------------------------------------

def write_data_quality_report(df_raw: pd.DataFrame, brand: str) -> Path:
    """Write reports/data_quality.md from the raw brand-filtered DataFrame."""
    n = len(df_raw)
    null_rates = (df_raw.isnull().sum() / n * 100).round(2)

    col_meanings = {
        "tweet_id": "Unique integer ID for each tweet",
        "author_id": "Twitter handle of the tweet author (brand or customer)",
        "inbound": "True = customer message; False = brand/outbound message",
        "created_at": "Timestamp string ('Tue Oct 31 22:10:47 +0000 2017')",
        "text": "Tweet text content (may contain @mentions, URLs, emoji)",
        "response_tweet_id": "Comma-separated IDs of direct replies to this tweet",
        "in_response_to_tweet_id": "Parent tweet ID (single integer or NaN if root)",
    }

    issues = []
    if df_raw["text"].isnull().any():
        issues.append(f"- `text`: {int(df_raw['text'].isnull().sum())} null values — "
                      "rows dropped during cleaning")
    if df_raw["created_at"].isnull().any():
        issues.append(f"- `created_at`: {int(df_raw['created_at'].isnull().sum())} "
                      "null timestamps — chronological sort uses tweet_id as tiebreak")
    if df_raw["in_response_to_tweet_id"].isnull().any():
        n_null_parent = int(df_raw["in_response_to_tweet_id"].isnull().sum())
        issues.append(f"- `in_response_to_tweet_id`: {n_null_parent:,} NaN values "
                      "(root tweets have no parent — expected)")

    # response_tweet_id dtype note
    issues.append("- `response_tweet_id`: stored as string because values can be "
                  "comma-separated lists (e.g. '5,7') when a tweet has multiple replies")

    schema_rows = "\n".join(
        f"| `{col}` | {df_raw[col].dtype} | {null_rates.get(col, 0):.1f}% | "
        f"{col_meanings.get(col, '')} |"
        for col in df_raw.columns
    )

    md = textwrap.dedent(f"""
    # Data Quality Report — `{brand}` brand rows

    **Total rows (brand-connected):** {n:,}
    **Brand messages (outbound):** {int((df_raw['author_id'] == brand).sum()):,}
    **Customer messages (inbound):** {int(df_raw['inbound'].sum()):,}

    ## Column Schema

    | Column | dtype | Null rate | Meaning |
    |---|---|---|---|
    {schema_rows}

    ## Known Issues & Handling

    {chr(10).join(issues) if issues else "No critical issues found."}

    ## Sampling & Reproducibility

    - Full dataset: ~3,003,124 rows  
    - Brand-connected subset loaded in two passes (see `src/data/loader.py`)  
    - No row-level random sampling at this stage — all brand-connected rows are kept  
    - Downstream splits use `seed={settings.sample_seed}` for reproducibility  

    *Generated by `src/data/stats.py`*
    """).strip()

    out = settings.reports_dir / "data_quality.md"
    out.write_text(md, encoding="utf-8")
    print(f"[stats] Data quality report -> {out}")
    return out


# ---------------------------------------------------------------------------
# Data stats report + charts
# ---------------------------------------------------------------------------

def write_data_stats_report(
    train: list[Thread],
    val: list[Thread],
    test: list[Thread],
    brand: str,
) -> Path:
    """Write reports/data_stats.md with counts + length distributions."""
    fig_dir = settings.reports_dir / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)

    all_splits = {"train": train, "val": val, "test": test}

    # --- compute stats ---
    stats: dict[str, dict] = {}
    for name, split in all_splits.items():
        msg_lengths = [len(m.text.split())
                       for t in split for m in t.messages]
        thread_lengths = [t.n_turns for t in split]
        stats[name] = {
            "n_threads": len(split),
            "n_messages": sum(thread_lengths),
            "n_customer_msgs": sum(
                1 for t in split for m in t.messages if m.role == "customer"
            ),
            "n_brand_msgs": sum(
                1 for t in split for m in t.messages if m.role == "brand"
            ),
            "msg_len_median": float(np.median(msg_lengths)) if msg_lengths else 0,
            "msg_len_p90": float(np.percentile(msg_lengths, 90)) if msg_lengths else 0,
            "thread_len_median": float(np.median(thread_lengths)) if thread_lengths else 0,
            "thread_len_max": int(max(thread_lengths)) if thread_lengths else 0,
            "multi_turn_pct": (
                sum(1 for t in split if t.n_turns >= 3) / max(len(split), 1) * 100
            ),
        }

    # --- message length distribution plot ---
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    colors = {"train": "#4C8BF5", "val": "#F5A623", "test": "#2ECC71"}

    for name, split in all_splits.items():
        msg_lens = [len(m.text.split()) for t in split for m in t.messages]
        axes[0].hist(msg_lens, bins=40, alpha=0.55, label=name,
                     color=colors[name], density=True)
    axes[0].set_xlabel("Message length (words)")
    axes[0].set_ylabel("Density")
    axes[0].set_title("Message Length Distribution")
    axes[0].legend()
    axes[0].set_xlim(0, 60)

    for name, split in all_splits.items():
        t_lens = [t.n_turns for t in split]
        axes[1].hist(t_lens, bins=range(1, 15), alpha=0.55, label=name,
                     color=colors[name], density=True)
    axes[1].set_xlabel("Thread length (turns)")
    axes[1].set_ylabel("Density")
    axes[1].set_title("Thread Length Distribution")
    axes[1].legend()

    plt.suptitle(f"{brand} - Data Split Statistics", fontsize=13)
    plt.tight_layout()
    fig_path = fig_dir / "data_distributions.png"
    plt.savefig(fig_path, dpi=120)
    plt.close()
    print(f"[stats] Distribution chart -> {fig_path}")

    # --- markdown ---
    split_table = (
        "| Split | Threads | Messages | Customer | Brand | "
        "Msg median len | Thread med. turns | Multi-turn % |\n"
        "|---|---|---|---|---|---|---|---|\n"
    )
    for name, s in stats.items():
        split_table += (
            f"| {name} | {s['n_threads']:,} | {s['n_messages']:,} | "
            f"{s['n_customer_msgs']:,} | {s['n_brand_msgs']:,} | "
            f"{s['msg_len_median']:.0f} | {s['thread_len_median']:.1f} | "
            f"{s['multi_turn_pct']:.1f}% |\n"
        )

    md = textwrap.dedent(f"""
    # Data Statistics Report — `{brand}`

    **Split strategy:** Conversation-level (full thread lives in one split).
    Stratified by turns-bucket (1 / 2 / 3-5 / 6+). Seed={settings.sample_seed}.

    ## Split Counts & Distributions

    {split_table}

    ## Length Distribution Charts

    ![Data distributions](figures/data_distributions.png)

    ## Notes

    - Threads truncated to ≤10 turns (see `src/data/threads.py: MAX_CONTEXT_TURNS`).
    - Only threads with ≥1 customer message are included.
    - Message length = whitespace-tokenised word count of cleaned text.
    - Multi-turn = thread has ≥3 messages.

    *Generated by `src/data/stats.py`*
    """).strip()

    out = settings.reports_dir / "data_stats.md"
    out.write_text(md, encoding="utf-8")
    print(f"[stats] Data stats report -> {out}")
    return out
